services:
  caddy:
    container_name: caddy-reverse-proxy
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.11.6 
    secrets:
      - cf_api_token
      - pve_root_ca
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "host"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

secrets:
  cf_api_token:
    file: ./secrets/cf_api_token.txt
  pve_root_ca:
    file: ./secrets/pve-root-ca.pem
